# Generated by Django 4.1.7 on 2023-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDiscription3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
    ]
