# Generated by Django 4.1.7 on 2023-02-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_datadiscription3_delete_datadiscription2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataDiscription3',
            new_name='DataDiscription',
        ),
    ]
